/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufsc.grad.compilator;

import java.io.File;

import br.ufsc.grad.compilator.model.LexicalAnalysis;
import br.ufsc.grad.compilator.model.SyntaxAnalysis;

public class App {

    public static void main(String[] args) {
        // Check for args
        if (args.length != 1) {
            System.out.println("Você precisa passar o destino do arquivo.");
            return;
        }

        // Check for file
        File f = new File(args[0]);

        if ((!f.exists() || f.isDirectory()) || !f.getName().toLowerCase().endsWith(".ccc")) {
            System.out.println("Arquivo invalido. Necessário ser <arquivo>.ccc");
            return;
        }

        try {
            // System.out.println("Lexical Analysis");
            LexicalAnalysis lexer = new LexicalAnalysis(f);

            lexer.analyse();

            // lexer.printTokenList();
            // lexer.printSymbolTable();

            System.out.println("Semantic Analysis");
            System.out.println();
            SyntaxAnalysis parser = new SyntaxAnalysis(lexer);
            parser.analyse();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
