/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufsc.grad.compilator;

import java.io.File;
import java.io.FileInputStream;

import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

@SuppressWarnings("deprecation")
public class App {

    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println("Você precisa passar o destino do arquivo.");
            return;
        }
        File f = new File(args[0]);
        if ((!f.exists() || f.isDirectory()) || !f.getName().toLowerCase().endsWith(".ccc")) {
            System.out.println("Arquivo invalido. Necessário ser <arquivo>.ccc");
            return;
        }
        try {
            try (FileInputStream is = new FileInputStream(f)) {
                ANTLRInputStream antlrIs = new ANTLRInputStream(is);
                CCC20201Lexer lexer = new CCC20201Lexer(antlrIs);
                CommonTokenStream tokens = new CommonTokenStream(lexer);
                CCC20201Parser parser = new CCC20201Parser(tokens);
                System.out.println(parser.program());
                // System.out.println(tree.getText());
            }
        } catch (Exception e) {

            e.printStackTrace();
        }
    }
}
